export interface GameLevel {
  levelname: string;
  level: number;
  difficulty: "Easy" | "Medium" | "Hard" | "Extreme" | "Very Hard";
  firstNum: number;
  secondNum: number;
  result: number;
}

export const AllLevels: GameLevel[] = [
  // EASY (1-10) - Addition & Simple Multiplication
  {
    levelname: "Street Start",
    level: 1,
    difficulty: "Easy",
    firstNum: 2,
    secondNum: 3,
    result: 5,
  },
  {
    levelname: "Warm Up",
    level: 2,
    difficulty: "Easy",
    firstNum: 4,
    secondNum: 2,
    result: 6,
  },
  {
    levelname: "Side Walk",
    level: 3,
    difficulty: "Easy",
    firstNum: 6,
    secondNum: 3,
    result: 18,
  },
  {
    levelname: "Morning Rush",
    level: 4,
    difficulty: "Easy",
    firstNum: 7,
    secondNum: 5,
    result: 12,
  },
  {
    levelname: "Simple Math",
    level: 5,
    difficulty: "Easy",
    firstNum: 5,
    secondNum: 5,
    result: 25,
  },
  {
    levelname: "Back Alley",
    level: 6,
    difficulty: "Easy",
    firstNum: 6,
    secondNum: 4,
    result: 24,
  },
  {
    levelname: "City Lights",
    level: 7,
    difficulty: "Easy",
    firstNum: 15,
    secondNum: 3,
    result: 5,
  },
  {
    levelname: "Fresh Mind",
    level: 8,
    difficulty: "Easy",
    firstNum: 12,
    secondNum: 4,
    result: 3,
  },
  {
    levelname: "Urban Crawl",
    level: 9,
    difficulty: "Easy",
    firstNum: 8,
    secondNum: 4,
    result: 2,
  },
  {
    levelname: "Smooth Ride",
    level: 10,
    difficulty: "Easy",
    firstNum: 6,
    secondNum: 6,
    result: 36,
  },

  // MEDIUM (11-20) - Mixed Operations, Moderate Numbers
  {
    levelname: "Brick Lane",
    level: 11,
    difficulty: "Medium",
    firstNum: 14,
    secondNum: 7,
    result: 2,
  },
  {
    levelname: "Mental Push",
    level: 12,
    difficulty: "Medium",
    firstNum: 8,
    secondNum: 5,
    result: 40,
  },
  {
    levelname: "Iron Core",
    level: 13,
    difficulty: "Medium",
    firstNum: 6,
    secondNum: 2,
    result: 12,
  },
  {
    levelname: "Overclocked",
    level: 14,
    difficulty: "Medium",
    firstNum: 9,
    secondNum: 6,
    result: 15,
  },
  {
    levelname: "Power Surge",
    level: 15,
    difficulty: "Medium",
    firstNum: 8,
    secondNum: 4,
    result: 32,
  },
  {
    levelname: "Focus Zone",
    level: 16,
    difficulty: "Medium",
    firstNum: 20,
    secondNum: 5,
    result: 15,
  },
  {
    levelname: "Neon Glow",
    level: 17,
    difficulty: "Medium",
    firstNum: 11,
    secondNum: 3,
    result: 33,
  },
  {
    levelname: "Logic Run",
    level: 18,
    difficulty: "Medium",
    firstNum: 25,
    secondNum: 5,
    result: 5,
  },
  {
    levelname: "Sharp Turn",
    level: 19,
    difficulty: "Medium",
    firstNum: 9,
    secondNum: 4,
    result: 36,
  },
  {
    levelname: "Grid Lock",
    level: 20,
    difficulty: "Medium",
    firstNum: 7,
    secondNum: 6,
    result: 42,
  },

  // HARD (21-30) - Higher Numbers, Complex Operations
  {
    levelname: "Night Shift",
    level: 21,
    difficulty: "Hard",
    firstNum: 30,
    secondNum: 6,
    result: 5,
  },
  {
    levelname: "Red Zone",
    level: 22,
    difficulty: "Hard",
    firstNum: 12,
    secondNum: 9,
    result: 108,
  },
  {
    levelname: "No Mercy",
    level: 23,
    difficulty: "Hard",
    firstNum: 22,
    secondNum: 11,
    result: 2,
  },
  {
    levelname: "Critical Mass",
    level: 24,
    difficulty: "Hard",
    firstNum: 14,
    secondNum: 8,
    result: 112,
  },
  {
    levelname: "Pressure Point",
    level: 25,
    difficulty: "Hard",
    firstNum: 21,
    secondNum: 7,
    result: 14,
  },
  {
    levelname: "Mental Heat",
    level: 26,
    difficulty: "Hard",
    firstNum: 9,
    secondNum: 9,
    result: 81,
  },
  {
    levelname: "Mind Burn",
    level: 27,
    difficulty: "Hard",
    firstNum: 32,
    secondNum: 4,
    result: 8,
  },
  {
    levelname: "Dark Matter",
    level: 28,
    difficulty: "Hard",
    firstNum: 18,
    secondNum: 5,
    result: 90,
  },
  {
    levelname: "Hard Wired",
    level: 29,
    difficulty: "Hard",
    firstNum: 27,
    secondNum: 9,
    result: 3,
  },
  {
    levelname: "Core Breaker",
    level: 30,
    difficulty: "Hard",
    firstNum: 35,
    secondNum: 7,
    result: 5,
  },

  // VERY HARD (31-40) - Advanced Calculations
  {
    levelname: "Last Stand",
    level: 31,
    difficulty: "Very Hard",
    firstNum: 16,
    secondNum: 5,
    result: 80,
  },
  {
    levelname: "Final Boss",
    level: 32,
    difficulty: "Very Hard",
    firstNum: 15,
    secondNum: 9,
    result: 135,
  },
  {
    levelname: "System Shock",
    level: 33,
    difficulty: "Very Hard",
    firstNum: 14,
    secondNum: 12,
    result: 168,
  },
  {
    levelname: "Terminal Velocity",
    level: 34,
    difficulty: "Very Hard",
    firstNum: 40,
    secondNum: 8,
    result: 5,
  },
  {
    levelname: "Point of No Return",
    level: 35,
    difficulty: "Very Hard",
    firstNum: 19,
    secondNum: 11,
    result: 30,
  },
  {
    levelname: "Endgame",
    level: 36,
    difficulty: "Very Hard",
    firstNum: 48,
    secondNum: 6,
    result: 8,
  },
  {
    levelname: "Mind Crusher",
    level: 37,
    difficulty: "Very Hard",
    firstNum: 13,
    secondNum: 13,
    result: 169,
  },
  {
    levelname: "Brain Apocalypse",
    level: 38,
    difficulty: "Very Hard",
    firstNum: 56,
    secondNum: 7,
    result: 8,
  },
  {
    levelname: "Final Circuit",
    level: 39,
    difficulty: "Very Hard",
    firstNum: 21,
    secondNum: 14,
    result: 294,
  },
  {
    levelname: "Insane Mode",
    level: 40,
    difficulty: "Very Hard",
    firstNum: 64,
    secondNum: 8,
    result: 8,
  },

  // EXTREME (41-50) - Peak Difficulty
  {
    levelname: "Celestial",
    level: 41,
    difficulty: "Extreme",
    firstNum: 17,
    secondNum: 15,
    result: 255,
  },
  {
    levelname: "Quantum Leap",
    level: 42,
    difficulty: "Extreme",
    firstNum: 90,
    secondNum: 9,
    result: 10,
  },
  {
    levelname: "Singularity",
    level: 43,
    difficulty: "Extreme",
    firstNum: 22,
    secondNum: 16,
    result: 352,
  },
  {
    levelname: "Event Horizon",
    level: 44,
    difficulty: "Extreme",
    firstNum: 81,
    secondNum: 9,
    result: 9,
  },
  {
    levelname: "Cosmic Storm",
    level: 45,
    difficulty: "Extreme",
    firstNum: 19,
    secondNum: 18,
    result: 342,
  },
  {
    levelname: "Transcendence",
    level: 46,
    difficulty: "Extreme",
    firstNum: 100,
    secondNum: 10,
    result: 10,
  },
  {
    levelname: "Beyond Reality",
    level: 47,
    difficulty: "Extreme",
    firstNum: 144,
    secondNum: 12,
    result: 12,
  },
  {
    levelname: "Divine Punishment",
    level: 48,
    difficulty: "Extreme",
    firstNum: 25,
    secondNum: 25,
    result: 625,
  },
  {
    levelname: "God Mode",
    level: 49,
    difficulty: "Extreme",
    firstNum: 256,
    secondNum: 16,
    result: 16,
  },
  {
    levelname: "The Creator",
    level: 50,
    difficulty: "Extreme",
    firstNum: 999,
    secondNum: 37,
    result: 27,
  },
];
